version: '3'

services:
  postgresql:
    image: postgres
    container_name: lesson
    volumes:
      - ./log-directory:/var/lib/postgresql/data
    ports:
      - '8080:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=mirage
      - POSTGRES_PASSWORD=34299
      - POSTGRES_DATABASE=postgres
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-lesson
    ports:
      - '6379-6379'
